services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      PGUSER: ${PGUSER} # postgres
      PGPASSWORD: ${PGPASSWORD} # postgres
      PGDATABASE: ${PGDATABASE} # postgres
      PGHOST: ${PGHOST} # localhost
      PGPORT: ${PGPORT} # 5432
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: ${REDIS_HOST} # redis
      REDIS_PORT: ${REDIS_PORT} # 6379
      PGUSER: ${PGUSER} # postgres
      PGPASSWORD: ${PGPASSWORD} # postgres
      PGDATABASE: ${PGDATABASE} # postgres
      PGHOST: ${PGHOST} # localhost
      PGPORT: ${PGPORT} # 5432

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    container_name: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      REDIS_HOST: ${REDIS_HOST} # redis
      REDIS_PORT: ${REDIS_PORT} # 6379
